ALTER TABLE "metrics" ADD COLUMN IF NOT EXISTS "source" VARCHAR(255);
ALTER TABLE "metrics" ADD COLUMN IF NOT EXISTS "ptTarget" DECIMAL(5,2);
ALTER TABLE "metrics" ADD COLUMN IF NOT EXISTS "ptMid" DECIMAL(5,2);
